name: docs build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  LearnData-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 7
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Configure npm registry
        run: pnpm config set registry https://registry.npmmirror.com

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |
          pnpm docs:build
          > docs/.vuepress/dist/.nojekyll

      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/.vuepress/dist

      - name: Deploy to blog-vercel
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: timpcfan/blog-vercel
          publish_branch: main
          publish_dir: docs/.vuepress/dist
          force_orphan: true
